"""Prepare masks and software-render the offline Purple Cougar v4 hull.

The geometry itself is generated by ``build_cougar_visual_hull_v4.mjs`` with
Three.js MarchingCubes in Node.  This Python companion uses Pillow only:

* ``prepare`` extracts clean binary masks and writes a calibration manifest.
* ``render`` reads the generated OBJ and makes neutral-clay orthographic views.
* ``all`` runs prepare -> Node geometry -> render.

No browser, localhost server, Blender process, or runtime asset is involved.
"""

from __future__ import annotations

from array import array
import argparse
import json
import math
import os
from pathlib import Path
import subprocess
from typing import Sequence

from PIL import Image, ImageChops, ImageDraw, ImageFilter, ImageFont


PROJECT = Path(__file__).resolve().parents[1]
ARTIFACTS = PROJECT / "artifacts" / "v4"
OUTPUT = ARTIFACTS / "node"
CARDINAL_SOURCE = ARTIFACTS / "purple-cougar-turnaround-v1.png"
OBLIQUE_SOURCE = ARTIFACTS / "purple-cougar-oblique-turnaround-v1.png"
NODE_BUILDER = PROJECT / "tools" / "build_cougar_visual_hull_v4.mjs"
MANIFEST = OUTPUT / "mask-manifest.json"
OBJ_OUTPUT = OUTPUT / "purple-cougar-visual-hull-v4.obj"
METRICS_OUTPUT = OUTPUT / "purple-cougar-visual-hull-v4-metrics.json"
CONTACT_SHEET = OUTPUT / "purple-cougar-visual-hull-v4-clay-contact-sheet.png"

INVERSE_SQRT_TWO = 1.0 / math.sqrt(2.0)
VIEW_DEFINITIONS = (
    {
        "name": "front",
        "source": "cardinal",
        "crop": (0, 0, 681, 510),
        "center_u": 339.5,
        "ground_v": 467.0,
        "pixels_per_height": 450.0,
        "projection": (0.0, 1.0),
    },
    {
        "name": "rear",
        "source": "cardinal",
        "crop": (0, 516, 681, 1024),
        "center_u": 339.5,
        "ground_v": 440.0,
        "pixels_per_height": 430.0,
        "projection": (0.0, -1.0),
        "remove_tail": "rear-center",
    },
    {
        "name": "left",
        "source": "cardinal",
        "crop": (687, 0, 1536, 510),
        "center_u": 396.25,
        "ground_v": 454.0,
        "pixels_per_height": 418.0,
        "projection": (-1.0, 0.0),
        "remove_tail": "high-u",
    },
    {
        "name": "right",
        "source": "cardinal",
        "crop": (687, 516, 1536, 1024),
        "center_u": 431.0,
        "ground_v": 438.0,
        "pixels_per_height": 416.0,
        "projection": (1.0, 0.0),
        "remove_tail": "low-u",
    },
    {
        "name": "fl45",
        "source": "oblique",
        "crop": (4, 4, 695, 557),
        "center_u": 446.0,
        "ground_v": 508.0,
        "pixels_per_height": 463.0,
        "projection": (-INVERSE_SQRT_TWO, INVERSE_SQRT_TWO),
    },
    {
        "name": "fr45",
        "source": "oblique",
        "crop": (706, 4, 1398, 557),
        "center_u": 241.0,
        "ground_v": 508.0,
        "pixels_per_height": 463.0,
        "projection": (INVERSE_SQRT_TWO, INVERSE_SQRT_TWO),
    },
    {
        "name": "rl45",
        "source": "oblique",
        "crop": (4, 566, 695, 1118),
        "center_u": 344.0,
        "ground_v": 472.0,
        "pixels_per_height": 420.0,
        "projection": (-INVERSE_SQRT_TWO, -INVERSE_SQRT_TWO),
    },
    {
        "name": "rr45",
        "source": "oblique",
        "crop": (706, 566, 1398, 1118),
        "center_u": 350.0,
        "ground_v": 472.0,
        "pixels_per_height": 420.0,
        "projection": (INVERSE_SQRT_TWO, -INVERSE_SQRT_TWO),
    },
)


def mask_bbox(mask: Image.Image) -> tuple[int, int, int, int]:
    bounds = mask.getbbox()
    if bounds is None:
        raise ValueError("Green-screen extraction produced an empty mask")
    left, top, right, bottom = bounds
    return left, top, right - 1, bottom - 1


def segment_green_screen(panel: Image.Image) -> Image.Image:
    red, green, blue = panel.convert("RGB").split()
    strongest_non_green = ImageChops.lighter(red, blue)
    chroma_distance = ImageChops.subtract(green, strongest_non_green)
    mask = chroma_distance.point(lambda value: 255 if value < 150 else 0, "L")
    # Native Pillow morphology strips whiskers/flyaways without Python pixel loops.
    return mask.filter(ImageFilter.MinFilter(3)).filter(ImageFilter.MaxFilter(3))


def remove_tail(mask: Image.Image, mode: str | None) -> Image.Image:
    if mode is None:
        return mask
    result = mask.copy()
    left, top, right, bottom = mask_bbox(result)
    draw = ImageDraw.Draw(result)
    if mode == "high-u":
        cut = round(left + 0.755 * (right - left))
        draw.rectangle((cut + 1, 0, result.width, result.height), fill=0)
    elif mode == "low-u":
        cut = round(right - 0.755 * (right - left))
        draw.rectangle((0, 0, cut - 1, result.height), fill=0)
    elif mode == "rear-center":
        center = 0.5 * (left + right)
        height = bottom - top
        width = right - left
        start = top + round(0.52 * height)
        for y in range(start, bottom + 1):
            progress = (y - top) / max(1, height)
            half_width = width * (0.05 if progress < 0.76 else 0.105)
            draw.line(
                (center - half_width, y, center + half_width, y),
                fill=0,
                width=1,
            )
    else:
        raise ValueError(f"Unsupported tail removal mode: {mode}")
    return result


def foreground_pixels(mask: Image.Image) -> int:
    histogram = mask.histogram()
    return histogram[255]


def prepare_masks() -> None:
    if not CARDINAL_SOURCE.exists() or not OBLIQUE_SOURCE.exists():
        raise FileNotFoundError("The clean cardinal and oblique sources are required")
    OUTPUT.mkdir(parents=True, exist_ok=True)
    sources = {
        "cardinal": Image.open(CARDINAL_SOURCE).convert("RGB"),
        "oblique": Image.open(OBLIQUE_SOURCE).convert("RGB"),
    }
    manifest_views: list[dict[str, object]] = []
    mask_images: list[tuple[str, Image.Image]] = []

    for definition in VIEW_DEFINITIONS:
        source = sources[str(definition["source"])]
        mask = segment_green_screen(source.crop(definition["crop"]))
        mask = remove_tail(mask, definition.get("remove_tail"))
        name = str(definition["name"])
        path = OUTPUT / f"mask-{name}.pgm"
        mask.save(path)
        mask_images.append((name, mask))
        manifest_views.append(
            {
                "name": name,
                "file": path.name,
                "width": mask.width,
                "height": mask.height,
                "bounds": list(mask_bbox(mask)),
                "foreground_pixels": foreground_pixels(mask),
                "center_u": definition["center_u"],
                "ground_v": definition["ground_v"],
                "pixels_per_height": definition["pixels_per_height"],
                "projection_forward_left": list(definition["projection"]),
                "pair": (
                    "front_rear"
                    if name in ("front", "rear")
                    else "left_right"
                    if name in ("left", "right")
                    else "diagonal_a"
                    if name in ("fl45", "rr45")
                    else "diagonal_b"
                ),
            }
        )

    manifest = {
        "version": "v4-node-visual-hull",
        "sources": {
            "cardinal": str(CARDINAL_SOURCE.relative_to(PROJECT)),
            "oblique": str(OBLIQUE_SOURCE.relative_to(PROJECT)),
        },
        "coordinate_system": {
            "x": "forward",
            "y": "up",
            "z": "animal-left",
        },
        "bounds": {
            "forward": [-0.64, 0.94],
            "animal_left": [-0.54, 0.54],
            "up": [-0.045, 1.055],
        },
        "tail_cutoff_forward": -0.60,
        "views": manifest_views,
    }
    MANIFEST.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    save_mask_sheet(mask_images)
    print(f"Prepared {len(mask_images)} masks: {MANIFEST}")


def save_mask_sheet(masks: Sequence[tuple[str, Image.Image]]) -> None:
    cell_width, cell_height = 430, 300
    gutter = 8
    sheet = Image.new(
        "RGB",
        (cell_width * 4 + gutter * 3, cell_height * 2 + gutter),
        "#111319",
    )
    draw = ImageDraw.Draw(sheet)
    font = ImageFont.load_default()
    for index, (name, mask) in enumerate(masks):
        row, column = divmod(index, 4)
        preview = mask.copy()
        preview.thumbnail((cell_width - 20, cell_height - 30))
        x = column * (cell_width + gutter) + (cell_width - preview.width) // 2
        y = row * (cell_height + gutter) + 22
        sheet.paste(Image.merge("RGB", (preview, preview, preview)), (x, y))
        draw.text((column * (cell_width + gutter) + 8, y - 16), name.upper(), font=font, fill="#d8cbd9")
    sheet.save(OUTPUT / "purple-cougar-visual-hull-v4-source-masks.png")


def parse_obj(
    path: Path,
) -> tuple[array, array, array]:
    vertices = array("f")
    normals = array("f")
    faces = array("I")
    with path.open("r", encoding="utf-8") as handle:
        for line in handle:
            if line.startswith("v "):
                _tag, x, y, z = line.split()
                vertices.extend((float(x), float(y), float(z)))
            elif line.startswith("vn "):
                _tag, x, y, z = line.split()
                normals.extend((float(x), float(y), float(z)))
            elif line.startswith("f "):
                tokens = line.split()[1:]
                indices = [int(token.split("/")[0]) - 1 for token in tokens]
                if len(indices) == 3:
                    faces.extend(indices)
                elif len(indices) > 3:
                    for index in range(1, len(indices) - 1):
                        faces.extend((indices[0], indices[index], indices[index + 1]))
    if not vertices or not faces:
        raise ValueError(f"OBJ contains no renderable geometry: {path}")
    return vertices, normals, faces


def vec3(data: array, index: int) -> tuple[float, float, float]:
    offset = index * 3
    return data[offset], data[offset + 1], data[offset + 2]


def normalize(vector: Sequence[float]) -> tuple[float, float, float]:
    length = math.sqrt(sum(value * value for value in vector))
    if length < 1.0e-12:
        return 0.0, 1.0, 0.0
    return tuple(value / length for value in vector)  # type: ignore[return-value]


def dot(left: Sequence[float], right: Sequence[float]) -> float:
    return sum(a * b for a, b in zip(left, right, strict=True))


def face_normal(
    a: Sequence[float],
    b: Sequence[float],
    c: Sequence[float],
) -> tuple[float, float, float]:
    ab = (b[0] - a[0], b[1] - a[1], b[2] - a[2])
    ac = (c[0] - a[0], c[1] - a[1], c[2] - a[2])
    return normalize(
        (
            ab[1] * ac[2] - ab[2] * ac[1],
            ab[2] * ac[0] - ab[0] * ac[2],
            ab[0] * ac[1] - ab[1] * ac[0],
        )
    )


def background_image(size: int) -> Image.Image:
    image = Image.new("RGB", (size, size))
    draw = ImageDraw.Draw(image)
    for y in range(size):
        t = y / max(1, size - 1)
        color = (
            round(14 + 18 * (1.0 - t)),
            round(17 + 17 * (1.0 - t)),
            round(23 + 18 * (1.0 - t)),
        )
        draw.line((0, y, size, y), fill=color)
    return image


def render_view(
    name: str,
    vertices: array,
    normals: array,
    faces: array,
    *,
    size: int = 640,
) -> tuple[Image.Image, dict[str, object]]:
    camera_definitions = {
        "front": ((1.0, 0.0, 0.0), (0.0, 0.0, 1.0)),
        "left": ((0.0, 0.0, 1.0), (-1.0, 0.0, 0.0)),
        "rear": ((-1.0, 0.0, 0.0), (0.0, 0.0, -1.0)),
        "right": ((0.0, 0.0, -1.0), (1.0, 0.0, 0.0)),
        "hero": (
            normalize((1.0, 0.0, 1.0)),
            normalize((-1.0, 0.0, 1.0)),
        ),
    }
    camera, screen_right = camera_definitions[name]
    screen_up = (0.0, 1.0, 0.0)
    points = [
        vec3(vertices, index) for index in range(len(vertices) // 3)
    ]
    projected = [
        (dot(point, screen_right), dot(point, screen_up), dot(point, camera))
        for point in points
    ]
    minimum_u = min(point[0] for point in projected)
    maximum_u = max(point[0] for point in projected)
    minimum_v = min(point[1] for point in projected)
    maximum_v = max(point[1] for point in projected)
    span_u = max(0.01, maximum_u - minimum_u)
    span_v = max(0.01, maximum_v - minimum_v)
    margin = 58
    scale = min((size - margin * 2) / span_u, (size - margin * 2) / span_v)
    center_u = 0.5 * (minimum_u + maximum_u)
    center_v = 0.5 * (minimum_v + maximum_v)
    pixel_bbox = [
        round(size * 0.5 + (minimum_u - center_u) * scale),
        round(size * 0.5 - (maximum_v - center_v) * scale),
        round(size * 0.5 + (maximum_u - center_u) * scale),
        round(size * 0.5 - (minimum_v - center_v) * scale),
    ]

    image = background_image(size)
    draw = ImageDraw.Draw(image)
    floor_y = size * 0.5 - (0.0 - center_v) * scale
    draw.ellipse(
        (
            margin * 0.6,
            floor_y - 14,
            size - margin * 0.6,
            floor_y + 22,
        ),
        fill=(10, 12, 16),
    )
    draw.line((0, floor_y + 7, size, floor_y + 7), fill=(63, 61, 66), width=2)

    light = normalize((0.78, 1.42, 0.88))
    base_color = (181, 164, 169)
    triangles: list[tuple[float, tuple[tuple[float, float], ...], tuple[int, int, int]]] = []
    for offset in range(0, len(faces), 3):
        ia, ib, ic = faces[offset], faces[offset + 1], faces[offset + 2]
        a, b, c = points[ia], points[ib], points[ic]
        geometric_normal = face_normal(a, b, c)
        facing = dot(geometric_normal, camera)
        if facing <= 0.002:
            continue
        if len(normals) >= len(vertices):
            normal_a = vec3(normals, ia)
            normal_b = vec3(normals, ib)
            normal_c = vec3(normals, ic)
            normal = normalize(
                tuple(
                    normal_a[axis] + normal_b[axis] + normal_c[axis]
                    for axis in range(3)
                )
            )
            if dot(normal, camera) < 0.0:
                normal = tuple(-value for value in normal)
        else:
            normal = geometric_normal
        screen = []
        for index in (ia, ib, ic):
            u, v, _depth = projected[index]
            screen.append(
                (
                    size * 0.5 + (u - center_u) * scale,
                    size * 0.5 - (v - center_v) * scale,
                )
            )
        depth = (projected[ia][2] + projected[ib][2] + projected[ic][2]) / 3.0
        diffuse = max(0.0, dot(normal, light))
        rim = max(0.0, 1.0 - facing) ** 2
        brightness = min(1.18, 0.43 + 0.54 * diffuse + 0.12 * rim)
        color = tuple(min(255, round(channel * brightness)) for channel in base_color)
        triangles.append((depth, tuple(screen), color))

    triangles.sort(key=lambda item: item[0])
    for _depth, polygon, color in triangles:
        draw.polygon(polygon, fill=color)

    font = ImageFont.load_default()
    draw.rounded_rectangle((18, 18, 92, 42), radius=10, fill=(16, 18, 24))
    draw.text((29, 27), name.upper(), font=font, fill=(232, 222, 229))
    return image, {
        "world_projection_bbox": [
            round(minimum_u, 6),
            round(minimum_v, 6),
            round(maximum_u, 6),
            round(maximum_v, 6),
        ],
        "world_projection_dimensions": [round(span_u, 6), round(span_v, 6)],
        "pixel_silhouette_bbox": pixel_bbox,
        "groundline_y": round(floor_y + 7),
    }


def render_contact_sheet() -> None:
    if not OBJ_OUTPUT.exists() or not METRICS_OUTPUT.exists():
        raise FileNotFoundError("Run the Node geometry builder before rendering")
    vertices, normals, faces = parse_obj(OBJ_OUTPUT)
    views = {}
    view_metrics = {}
    for name in ("front", "left", "rear", "right", "hero"):
        image, projection_metrics = render_view(name, vertices, normals, faces)
        path = OUTPUT / f"purple-cougar-visual-hull-v4-clay-{name}.png"
        image.save(path)
        views[name] = image
        view_metrics[name] = {
            **projection_metrics,
            "file": str(path.relative_to(PROJECT)),
        }

    gutter = 8
    cell = next(iter(views.values())).width
    sheet = Image.new("RGB", (cell * 2 + gutter, cell * 2 + gutter), "#090b0f")
    sheet.paste(views["front"], (0, 0))
    sheet.paste(views["left"], (cell + gutter, 0))
    sheet.paste(views["rear"], (0, cell + gutter))
    sheet.paste(views["right"], (cell + gutter, cell + gutter))
    sheet.save(CONTACT_SHEET)

    metrics = json.loads(METRICS_OUTPUT.read_text(encoding="utf-8"))
    metrics["review"] = {
        "disposition": "rejected-research-evidence",
        "promotion_allowed": False,
        "renderer": "Pillow CPU orthographic painter",
        "contact_sheet": str(CONTACT_SHEET.relative_to(PROJECT)),
        "views": ["front", "left", "rear", "right"],
        "hero": str(
            (
                OUTPUT / "purple-cougar-visual-hull-v4-clay-hero.png"
            ).relative_to(PROJECT)
        ),
        "resolution_each": [cell, cell],
        "silhouette_metrics": view_metrics,
    }
    METRICS_OUTPUT.write_text(
        json.dumps(metrics, indent=2) + "\n",
        encoding="utf-8",
    )
    print(f"Rendered clay contact sheet: {CONTACT_SHEET}")


def run_node(resolution: int) -> None:
    environment = os.environ.copy()
    environment["COUGAR_HULL_RESOLUTION"] = str(resolution)
    subprocess.run(
        ["node", str(NODE_BUILDER)],
        cwd=PROJECT,
        env=environment,
        check=True,
    )


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "stage",
        choices=("all", "prepare", "render"),
        nargs="?",
        default="all",
    )
    parser.add_argument(
        "--resolution",
        type=int,
        default=96,
        help="MarchingCubes grid resolution (64-112, default: 96)",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    resolution = max(64, min(112, args.resolution))
    if args.stage in ("all", "prepare"):
        prepare_masks()
    if args.stage == "all":
        run_node(resolution)
    if args.stage in ("all", "render"):
        render_contact_sheet()


if __name__ == "__main__":
    main()
